//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeacherReward.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Deduction
    {
        public string ID { get; set; }

		[Range(0,30)]
        public double Supervisior { get; set; }
		[Range(0,20)]
        public double Accident { get; set; }

		[Required(ErrorMessage = "请填写备注")]
		[StringLength(30, ErrorMessage = "长度不能大于30个字符")]
		public string SuperComment { get; set; }

		[Required(ErrorMessage = "请填写备注")]
		[StringLength(30, ErrorMessage = "长度不能大于30个字符")]
		public string AccidentComment { get; set; }
    }
}
