//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeacherReward.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;
	using System.ComponentModel.DataAnnotations;

	public partial class TeacherCrosswiseTaskInfo {
		public string ID { get; set; }

		public string CTaskName { get; set; }
		public string CTaskLevel { get; set; }
		[StringLength(20, ErrorMessage = "长度不能大于20个字符")]
		public string CTaskStartTime { get; set; }
		[StringLength(20, ErrorMessage = "长度不能大于20个字符")]
		public string CTaskEndTime { get; set; }
		[StringLength(30, ErrorMessage = "长度不能大于30个字符")]
		public string CTaskComment { get; set; }
	}
}
