//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeacherReward.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;
	using System.ComponentModel.DataAnnotations;

	public partial class TeacherProjectInfo {
		public string ID { get; set; }

		[StringLength(25, ErrorMessage = "长度不能大于25个字符")]
		public string Project1Name { get; set; }
		public string Project1Level { get; set; }
		[StringLength(20, ErrorMessage = "长度不能大于20个字符")]
		public string Project1StartTime { get; set; }
		[StringLength(20, ErrorMessage = "长度不能大于20个字符")]
		public string Project1EndTime { get; set; }
		public string Project1Role { get; set; }
		[StringLength(30, ErrorMessage = "长度不能大于30个字符")]
		public string Project1Comment { get; set; }

		[StringLength(25, ErrorMessage = "长度不能大于25个字符")]
		public string Project2Name { get; set; }
		public string Project2Level { get; set; }
		[StringLength(20, ErrorMessage = "长度不能大于20个字符")]
		public string Project2StartTime { get; set; }
		[StringLength(20, ErrorMessage = "长度不能大于20个字符")]
		public string Project2EndTime { get; set; }
		public string Project2Role { get; set; }
		[StringLength(30, ErrorMessage = "长度不能大于30个字符")]
		public string Project2Comment { get; set; }

		[StringLength(25, ErrorMessage = "长度不能大于25个字符")]
		public string Project3Name { get; set; }
		public string Project3Level { get; set; }
		[StringLength(20, ErrorMessage = "长度不能大于20个字符")]
		public string Project3StartTime { get; set; }
		[StringLength(20, ErrorMessage = "长度不能大于20个字符")]
		public string Project3EndTime { get; set; }
		public string Project3Role { get; set; }
		[StringLength(30, ErrorMessage = "长度不能大于30个字符")]
		public string Project3Comment { get; set; }

		[StringLength(25, ErrorMessage = "长度不能大于25个字符")]
		public string Project4Name { get; set; }
		public string Project4Level { get; set; }
		[StringLength(20, ErrorMessage = "长度不能大于20个字符")]
		public string Project4StartTime { get; set; }
		[StringLength(20, ErrorMessage = "长度不能大于20个字符")]
		public string Project4EndTime { get; set; }
		public string Project4Role { get; set; }
		[StringLength(30, ErrorMessage = "长度不能大于30个字符")]
		public string Project4Comment { get; set; }
	}
}
