//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeacherReward.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;
	using System.ComponentModel.DataAnnotations;

	public partial class TeacherTaskInfo {
		public string ID { get; set; }

		[StringLength(20, ErrorMessage = "长度不能大于20个字符")]
		public string Task1Name { get; set; }
		[StringLength(20, ErrorMessage = "长度不能大于20个字符")]
		public string Task1StartTime { get; set; }
		[StringLength(20, ErrorMessage = "长度不能大于20个字符")]
		public string Task1EndTime { get; set; }
		public string Task1Level { get; set; }
		public string Task1Role { get; set; }
		[StringLength(30, ErrorMessage = "长度不能大于30个字符")]
		public string Task1Comment { get; set; }

		[StringLength(20, ErrorMessage = "长度不能大于20个字符")]
		public string Task2Name { get; set; }
		[StringLength(20, ErrorMessage = "长度不能大于20个字符")]
		public string Task2StartTime { get; set; }
		[StringLength(20, ErrorMessage = "长度不能大于20个字符")]
		public string Task2EndTime { get; set; }
		public string Task2Level { get; set; }
		public string Task2Role { get; set; }
		[StringLength(30, ErrorMessage = "长度不能大于30个字符")]
		public string Task2Comment { get; set; }

		[StringLength(20, ErrorMessage = "长度不能大于20个字符")]
		public string Task3Name { get; set; }
		[StringLength(20, ErrorMessage = "长度不能大于20个字符")]
		public string Task3StartTime { get; set; }
		[StringLength(20, ErrorMessage = "长度不能大于20个字符")]
		public string Task3EndTime { get; set; }
		public string Task3Level { get; set; }
		public string Task3Role { get; set; }
		[StringLength(30, ErrorMessage = "长度不能大于30个字符")]
		public string Task3Comment { get; set; }

		[StringLength(20, ErrorMessage = "长度不能大于20个字符")]
		public string Task4Name { get; set; }
		[StringLength(20, ErrorMessage = "长度不能大于20个字符")]
		public string Task4StartTime { get; set; }
		[StringLength(20, ErrorMessage = "长度不能大于20个字符")]
		public string Task4EndTime { get; set; }
		public string Task4Level { get; set; }
		public string Task4Role { get; set; }
		[StringLength(30, ErrorMessage = "长度不能大于30个字符")]
		public string Task4Comment { get; set; }
	}
}
