//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeacherReward.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;
	using System.ComponentModel.DataAnnotations;

	public partial class TeacherTaskInfo
    {
        public string ID { get; set; }
		[MaxLength(20, ErrorMessage = "最大长度20个字符")]
        public string Task1Name { get; set; }
		[MaxLength(15, ErrorMessage = "最大长度15个字符")]
		public string Task1StartTime { get; set; }
		[MaxLength(15, ErrorMessage = "最大长度15个字符")]
		public string Task1EndTime { get; set; }
        public string Task1Level { get; set; }
        public string Task1Role { get; set; }
		[MaxLength(20, ErrorMessage = "最大长度20个字符")]
		public string Task2Name { get; set; }
		[MaxLength(15, ErrorMessage = "最大长度15个字符")]
		public string Task2StartTime { get; set; }
		[MaxLength(15, ErrorMessage = "最大长度15个字符")]
		public string Task2EndTime { get; set; }
        public string Task2Level { get; set; }
        public string Task2Role { get; set; }
		[MaxLength(20, ErrorMessage = "最大长度20个字符")]
		public string Task3Name { get; set; }
		[MaxLength(15, ErrorMessage = "最大长度15个字符")]
		public string Task3StartTime { get; set; }
		[MaxLength(15, ErrorMessage = "最大长度15个字符")]
		public string Task3EndTime { get; set; }
        public string Task3Level { get; set; }
        public string Task3Role { get; set; }
		[MaxLength(20, ErrorMessage = "最大长度20个字符")]
		public string Task4Name { get; set; }
		[MaxLength(15, ErrorMessage = "最大长度15个字符")]
		public string Task4StartTime { get; set; }
		[MaxLength(15, ErrorMessage = "最大长度15个字符")]
		public string Task4EndTime { get; set; }
        public string Task4Level { get; set; }
        public string Task4Role { get; set; }
    }
}
