//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeacherReward.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;
	using System.ComponentModel.DataAnnotations;

    public partial class TeacherInfo
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public int Depart { get; set; }
        public int ShiDe { get; set; }

		[DisplayName("课时量")]
		[Required(ErrorMessage = "课时量不能为空")]
        public int baseTeachingTime { get; set; }
        public int extTeachingTime { get; set; }
        public int BossScore { get; set; }
        public int SuperScore { get; set; }
        public int StuScore { get; set; }
        public int DutyTime { get; set; }
        public int Prize { get; set; }
        public double baseProject { get; set; }
        public double extProject { get; set; }
        public int baseTeachThesis { get; set; }
        public int extTeachThesis { get; set; }
        public int TeachingAward { get; set; }
        public double basePublishThesis { get; set; }
        public double extPublishThesis { get; set; }
        public double baseTask { get; set; }
        public double extTask { get; set; }
        public double CrosswiseTask { get; set; }
        public int Showup { get; set; }
        public int DepartWorks { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
